<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TodoController;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

// Redirect root to login
Route::get('/', fn() => redirect()->route('login'));

// Dashboard (auth + verified)
Route::get('/dashboard', fn() => Inertia::render('Dashboard'))
    ->middleware(['auth', 'verified'])
    ->name('dashboard');

// Profile routes (auth required)
Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

// Todos routes (auth + verified)
Route::middleware(['auth', 'verified'])->group(function () {
    // List & create todos
    Route::get('/todos', [TodoController::class, 'index'])->name('todos.index');
    Route::post('/todos', [TodoController::class, 'store'])->name('todos.store');

    // Export
    Route::get('/todos/export', [TodoController::class, 'export'])->name('todos.export');

    // Single todo routes (show, update, delete)
    Route::get('/todos/{todo}', [TodoController::class, 'show'])
        ->middleware('can:view,todo')->name('todos.show');

    Route::put('/todos/{todo}', [TodoController::class, 'update'])
        ->middleware('can:update,todo')->name('todos.update');

    Route::delete('/todos/{todo}', [TodoController::class, 'destroy'])
        ->middleware('can:delete,todo')->name('todos.destroy');
});

// Auth routes (generated by Breeze)
require __DIR__.'/auth.php';
